{
 "title": "JVM Overview (OpenTelemetry) / Workload",
 "description": "Dashboard for JVM metrics with Prometheus / OpenTelemetry instrumentation",
 "tags": [
  "JVM",
  "open-telemetry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "workload",
    "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\", workload_type=\"$type\"}, workload)"
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(global_cluster_info{cluster_name=\"$cluster_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": {
     "query": "label_values(global_cluster_info, cluster_name)"
    }
   },
   {
    "name": "gc_action",
    "query": {
     "query": "label_values(process_runtime_jvm_gc_duration_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}, action)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime{cluster=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time{cluster=\"$cluster\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{cluster=\"$cluster\", namespace=\"$namespace\"} * 100"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "process_runtime_jvm_system_cpu_utilization{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "CPU utilization (whole system)"
    },
    {
     "expr": "process_runtime_jvm_cpu_utilization{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "JVM CPU utilization"
    }
   ]
  },
  {
   "title": "Average CPU load of the whole system for the last minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "process_runtime_jvm_system_cpu_load_1m{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "Average CPU load"
    }
   ]
  },
  { "title": "Memory pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Heap memory used / commited / max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(process_runtime_jvm_memory_usage{cluster=\"$cluster\", namespace=\"$namespace\",type=\"heap\"})",
     "legendFormat": "Heap used"
    },
    {
     "expr": "sum(process_runtime_jvm_memory_committed{cluster=\"$cluster\", namespace=\"$namespace\",type=\"heap\"})",
     "legendFormat": "Heap committed"
    },
    {
     "expr": "sum(process_runtime_jvm_memory_limit{cluster=\"$cluster\", namespace=\"$namespace\",type=\"heap\"})",
     "legendFormat": "Heap max obtainable"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_memory_usage{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{ type }} - {{ pool }}"
    }
   ]
  },
  {
   "title": "Memory committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_memory_committed{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{ type }} - {{ pool }}"
    }
   ]
  },
  {
   "title": "Max obtainable memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_memory_limit{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "{{ type }} - {{ pool }}"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Number of executing threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "process_runtime_jvm_threads_count{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "Daemon: {{daemon}}"
    }
   ]
  },
  { "title": "Garbage collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "JVM garbage collection duration - $gc_action",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "repeat": "gc_action",
   "targets": [
    {
     "expr": "sum(round(rate(jvm_gc_pause_bucket{cluster=\"$cluster\", namespace=\"$namespace\"}[$__interval]) * $__interval_ms / 1000)) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Number of classes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_classes_current_loaded{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "Currently loaded"
    },
    {
     "expr": "process_runtime_jvm_classes_loaded_total{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "Loaded since JVM start"
    },
    {
     "expr": "process_runtime_jvm_classes_unloaded_total{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "Unloaded since JVM start"
    }
   ]
  }
 ]
}