scrape_configs:
  - job_name: 'java'
    scrape_interval: 10s
    static_configs:
      - targets: ['adserviceotel:9464']
  - job_name: 'java-jmx'
    scrape_interval: 10s
    static_configs:
      - targets: ['adservicejmx:8088']
  - job_name: 'springboot-jvm'
    scrape_interval: 10s
    static_configs:
      - targets: ['adservicejmx:8999']

