version: "2"
services:
  adservice:
    container_name: adservice
    image: ghcr.io/openinsight-proj/demo:pr-adservice-v2
    environment:
      - JAVA_TOOL_OPTIONS="-javaagent:/app/jmx_prometheus_javaagent-0.17.0.jar=8088:/app/prometheus-jmx-config.yaml"
    ports:
      - "8088:8088"
      - "8999:8999"
      - "8080:8080"
      - "8888:8888"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.30.3
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
